name: FirstCICD
on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
     
      - name: Authentication DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
        
    
      
      - name: ConstructionDockerImage
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            josealceu/live-kube-news:${{github.run_number}}
            josealceu/live-kube-news:latest
